apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whatpod
spec:
  destination:
    name: ''
    namespace: mushroomhead
    server: https://kubernetes.default.svc
  source:
    path: whatpod
    repoURL: https://github.com/kcsoukup/argocd-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
