{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.ingress.annotations }}
    annotations: {{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host.name | quote }}
    http:
      paths:
        - path: {{ .Values.ingress.host.path }}
          pathType: {{ .Values.ingress.host.pathType }}
          backend:
            service:
              name: {{ template "fullname" . }}
              port:
                number: {{ $.Values.service.targetPort }}
{{- end }}
