#
#  Helm Chart: primary values.yaml
#
replicaCount: 2
namespace: mushroomhead

image:
  repository: kcsoukup/python-docker
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  annotations: {}

ingress:
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  host:
    name: doom-goose.damage.inc
    path: /
    pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes: {}

volumeMounts: {}

secrets:
  enabled: false
  # name:
  # data:
  #   key1: value
  #   key2: value
